### ISSUE TITLE
Accent color text in preview wrong

### ISSUE THREAD

**Issue by bradhogan** [richtabor/wabi#14]
Looks like if you select the accent color when editing a block (p or H1 for example), the variable shows vs. the hexcode for the accent color. 
<img width="318" alt="Screen Shot 2022-03-21 at 10 50 54 AM" src="https://user-images.githubusercontent.com/1781226/159316262-ea364587-e7e8-45b7-8f62-3c7be5378de2.png">

**Comment by richtabor** [comment]
Hey @bradley2083 that’s actually intentional — as that color’s value depends on the post’s accent color. For example, if you choose the purple color for that post, then any blocks using the “Accent” color would be painted that purple. And if you used the blue accent color on the post, that same block’s color would automatically change to blue. 

Does that clear it up?

**Comment by bradley2083** [comment]
@richtabor Thanks for the reply.  I understand the function of the accent color I guess I was just thinking the display text should show the hex to stay consistent with the other options.  But maybe you're doing that so people know to use the var(--custom--color--accent) in the stylesheet should they want to add styles with that color.

**Comment by richtabor** [comment]
> But maybe you're doing that so people know to use the var(--custom--color--accent) in the stylesheet should they want to add styles with that color.

The value of that color picker _is_ the CSS property — it's not a hex value. That accent color is set by which color you've selected to display as the post's accent color here: 

<img width="570" alt="CleanShot 2022-03-24 at 11 32 07@2x" src="https://user-images.githubusercontent.com/1813435/159952543-cc01bca7-cf44-498b-8438-ee2da93e2614.png">

You wouldn't need to modify the CSS selector here, but rather edit/choose an accent color. 

Hope this is clearer :)

**Comment by bradley2083** [comment]
I get what you're saying. My original ticket was just saying that I thought the hex for the accent color should be displayed when you choose it (like in my screenshot) rather than "var(--wp--custom--color--accent)" - I think that makes sense to a developer but if it's a normal user of the theme, it seems like that would be confusing to them since the other default colors show the hex rather than "var(--wp--preset--color--primary)" etc.
